### ISSUE TITLE
[BUG] Nether

### ISSUE THREAD

**Issue by xotrikspl** [AMPZNetwork/All-The-Fabric-4#1]
**Describe the bug**
Entering nether only shows the loading screen.
If I disable the game, it will teleport me to the first location when I re-enter(first checkpoint)

**To Reproduce**
1. get obsidian
2. build nether portal
3. enter nether
4. loading screen and nothing loading

**Expected behavior**
only loading screen

**Crash Log**
https://hastebin.skyra.pw/cosebekere.bash

**Screenshots**
in this case, a screenshot should not be needed

**Basic Informations (please complete the following information):**
 - OS: Windows 10 Pro 64bit
 - Fossilized Version: v1
 - Platform: MultiMC
 - Extra mods added by you: i don't have

**Comment by xotrikspl** [comment]
I've been waiting for about an hour for him to get transferred to the nether. I noticed that the loading screen is playing sounds.

**Comment by LabsZero** [comment]
I can't seem to replicate the issue.  Can you try another launcher to be sure it's an issue with the pack.

**Comment by xotrikspl** [comment]
I checked my world on ATLauncher and there was the same problem too.
I fixed this bug by deleting the DIM-1 folder (nether world)
