### ISSUE TITLE
[BUG?] REI blank?

### ISSUE THREAD

**Issue by thekrugers** [AMPZNetwork/All-The-Fabric-4#5]
**Describe the bug**
Honestly, I don't know if this is a bug or a design decision. Whenever I look at a new pack, the first thing I do is make a creative world and open REI/JEI to look at what's available in terms of blocks and items. With this pack, REI shows no blocks or items. At first, I thought it may only show "known" items, so I grabbed some logs, made planks and make a crafting table. Still no logs, planks or crafting table in REI.

**To Reproduce**
1. Install All The Fabric 4
2. Start a new world
3. Open inventory
4. No items in REI on the right

**Expected behavior**
A full listing of blocks/items in REI, or at least known blocks/items (with some way of showing the full list in creative mode)

**Crash Log**
Not a crash

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - All The Fabric 4 Version: V7
 - Platform: ATLauncher
 - Extra mods added by you: None

**Comment by LabsZero** [comment]
This is a known issue and is being looked into.
