### ISSUE TITLE
[BUG]? Or Compatibility issue?

### ISSUE THREAD

**Issue by anoththebarbarian** [AMPZNetwork/All-The-Fabric-4#6]
**Describe the bug**
When looking up a recipe in JEI, using either the r shortcut or u shortcut, none of the recipes are present for items used in, or created by, Tech Reborn machines.

For example, Coal Dust is visible in the JEI menu, but the fact that it is made in the Tech Reborn Grinder does not come up at all.

**To Reproduce**
1. Start game
2. Search up a tech reborn dust
3. Use the hot key to choose how to make the dust, or what the dust is used for
4. Notice that there is no recipe or usage of a tech reborn machine

**Expected behavior**
For each of the tech reborn machines there are numerous recipes both creating and using tech reborn items - and often one only knows how to make these items through a JEI or similar mod pointing out how to get those items.

**Crash Log**
If the bug includes a crash, please paste or link it here.

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows
 - All The Fabric 4 Version V7.1
 - Platform AT Launcher
 - Extra mods added by you: none

**Comment by LabsZero** [comment]
Seems to be a compatibility issue with tech reborn and JEI. I’m looking into getting REI back in the pack again.

**Comment by LabsZero** [comment]
New patch update has been released that should fix this issue. *Closing issue*
