### ISSUE TITLE
Towns and Towers causes installation errors on Modrinth

### ISSUE THREAD

**Issue by ApexdaGamer** [AMPZNetwork/All-The-Fabric-4#8]
## Bug Description
When I try to install on Modrinth, it says that the hash for the install of Towns and Towers is different from the one it's supposed to be.
I can't figure out why, and there's no way to remove that mod except for the mod creators.

## Reproduction Steps
To replicate the problem, follow these steps:
1. Navigate to Modrinth
2. Click on Version 7+
3. Click install.
4. error.

## Expected Outcome
I thought it would've installed as normal, like V6 and below does.

## Basic Information (please fill in the following details):
 - Operating System: Windows
 - All The Fabric 4 Version: v8
 - Platform: Modrinth

**Comment by LabsZero** [comment]
Thank you for youur report i will look into a patch asap

**Comment by LabsZero** [comment]
Issue has been resoved in v9 
https://modrinth.com/modpack/all-the-fabric-4/version/V9 

Once again thank you for reporting this issue.
